### ISSUE TITLE
Integrate Aloha with H2O

### ISSUE THREAD

**Issue by jmorra** [eHarmony/aloha#11]
Add the ability to build H2O Aloha models.  This should have all the same support that VW currently has.

**Comment by deaktator** [comment]
# Integrating H<sub>2</sub>O and Aloha

We need to create a separate module like the [aloha-vw-jni](https://github.com/eHarmony/aloha/tree/master/aloha-vw-jni) module.  This wil prevent unnecessary dependencies being pulled in for users who don't need H<sub>2</sub>O's power.

## Proposed Aloha JSON

``` json
{
  "modelType": "h2o",
  "modelId": { "id": 0, "name": "my-h20-model" },
  "h2oApiLevel": "HighLevel",
  "features": {
    "distance": "sos2(log(${match.distance}), 1, 10, 1)",
    "user_eye_color": "${user.eye_color}"
  },
  "MODEL REPRESENTATION": "MODEL REPRESENTATION HERE"
}
```

### h2oApiLevel field

Allows user to choose between H<sub>2</sub>O's high-level `RowData`-based API or a lower-level `double[]`-based API.  While this shouldn't matter to the user, it'll allow Aloha to select between implementations.  This will be an optional field and initially, the default value will be to use the high-level `RowData`-based API.  If performance is deemed inadequate, we can write a second implementation based on `double[]`.  Then, we'll add an enumerated type constant.  Once the low-level API is mature, we can switch the default to it, so that if the user doesn't care, it will default to the performant one.

## Sparse Data

Notice `sos2` in the `features` of the Aloha specification.  This can return multiple key-value pairs.  For instance: 

``` scala
{ "distance=1" -> 0.4, "distance=2" -> 0.6 }
```

We need to figure out how well H<sub>2</sub>O deals with sparse data. It is especially important to explore this for dimensions / values not seen in the training data before or ones that have been regularized out.  The javadoc says, 

> For categorical columns, the value must be a String with the **same names as seen in the training data**. 
> 
> **It is not allowed to use new categorical levels unseen during training** (_this will result in a_
> **PredictUnknownCategoricalLevelException** _when one of the predict methods is called_).

So we need to be extremely careful do avoid introducing covariate data at prediction time that was never seen at training time.  This is important when dealing with text and enumerated types.

## H<sub>2</sub>O Model Representation

What's still up in the air is the model representation.  Do we want to encode the H<sub>2</sub>O model at:
1. _source code_ level 
2. _class file_ level

### Source Code Level Model Representation

If dealing with the Java source, we need to compile it.  This can be done at runtime via `javax.tools.JavaCompiler`.  See [javadoc](http://docs.oracle.com/javase/7/docs/api/javax/tools/JavaCompiler.html).  This is for java 1.6+ (_JSR 199_).  We can also explore other options.  See the _Compiling fully in memory with javax.tools.JavaCompiler_ [Stack Overflow thread](http://stackoverflow.com/questions/12173294/compiling-fully-in-memory-with-javax-tools-javacompiler) for more details.  

### Class File Level Model Representation

We can try to insist the H<sub>2</sub>O models are precompiled and then we copy the class files locally.  This can be problematic, especially if the H<sub>2</sub>O models make use of inner classes because this will result in multiple class files per source file.

## Classloading

Either of the above methods are possible.  I lean toward the source level representation.  One issue that may arise is the classloading of the model class files.  We need to ensure this works in a bunch of diverse environments with managed class loaders.  This should be tested in Spark, Hadoop, web containers (Tomcat, Jetty, etc).  We also want to ensure that the H<sub>2</sub>O dependencies are on the classpath so that compilation doesn't run into linking errors / ClassNotFoundExceptions.

## Caching Compiled Models

This may be useful to think about.  While it's likely that the java compilation is an order of magnitude faster than the scala-based feature compilation, this may still be necessary.  This should only be done after assessing startup time.

## Inline vs Model Location

Like the [VW JNI model ](https://github.com/eHarmony/aloha/tree/master/aloha-vw-jni) we should probably have a mechanism to load models via a serialized base64-encoded string or loading from a [FsInstance](https://github.com/eHarmony/aloha/blob/master/aloha-core/src/main/scala/com/eharmony/aloha/io/fs/package.scala).  This latter will allow us to inject the model location in the environment configuration using Chef, Puppet, Ansible, etc.  

This could look something like:
- `"modelCode": "b64 encoded string containing java source"`
- `"modelUrl": "Apache VFS1 or VFS2 URL"`

## Automatically Determining Prediction Type

> Each generated model is of exactly one category. Only one of the different predict calls works with 
> that category. For example, a model of category Binomial can only respond properly to 
> predictBinomial(). Attempting to call the wrong predict method for a model results in a 
> [PredictWrongModelCategoryException](http://h2o-release.s3.amazonaws.com/h2o/master/3141/docs-website/h2o-genmodel/javadoc/hex/genmodel/easy/exception/PredictWrongModelCategoryException.html).

At initialization time, we can try the different predication types and determine the one that works and use that predication method from then on.  This will use a chain-of-responsibility pattern to fine the first one.  If no prediction method works, an exception will be thrown at Aloha model construction time.

## Type Hinting for Continuous vs Categorical Variables

There may be a need to provide type hinting in the Aloha feature specifications to tell whether we are creating key-value pairs where the values are continuous or categorical.  If this is necessary, we'll most likely have to add acceptable values for the categorical variables to avoid `PredictUnknownCategoricalLevelException`s.

## H<sub>2</sub>O Javadoc

### H<sub>2</sub>O Javadoc for _Easy_ Wrapper (High Level API)

This is a high-level mapping that is based on `Map<String, Object>` rather than `double[]`.  This produces the `data` array (`double[]`) that is passed to the `score0` function in the generated H<sub>2</sub>O models. 
- [RowData](http://h2o-release.s3.amazonaws.com/h2o/master/3141/docs-website/h2o-genmodel/javadoc/hex/genmodel/easy/RowData.html)
- [EasyPredictModelWrapper](http://h2o-release.s3.amazonaws.com/h2o/master/3141/docs-website/h2o-genmodel/javadoc/hex/genmodel/easy/EasyPredictModelWrapper.html)

### H<sub>2</sub>O Javadoc for _Easy_ Prediction Interface:

These reside in the `hex.genmodel.easy.prediction` package. The interesting ones for us are:
- [Binomial Classification](http://h2o-release.s3.amazonaws.com/h2o/master/3141/docs-website/h2o-genmodel/javadoc/hex/genmodel/easy/prediction/BinomialModelPrediction.html)
- [Multinomial Classification](http://h2o-release.s3.amazonaws.com/h2o/master/3141/docs-website/h2o-genmodel/javadoc/hex/genmodel/easy/prediction/MultinomialModelPrediction.html)
- [Regression](http://h2o-release.s3.amazonaws.com/h2o/master/3141/docs-website/h2o-genmodel/javadoc/hex/genmodel/easy/prediction/RegressionModelPrediction.html)
